package nianyang.mny.infra.dao;

import java.util.List;
import nianyang.mny.infra.baseDO.CharacterDO;
import nianyang.mny.infra.baseDO.CharacterParam;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author sikou
 */
public interface CharacterDAO {
    /**
     * 根据WHERE条件COUNT
     * @param characterParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(CharacterParam characterParam);

    /**
     * 根据WHERE条件删除
     * @param characterParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(CharacterParam characterParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(CharacterDO record);

    /**
     * 根据字段选择性插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(CharacterDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param characterParam
     * @return
     *
     * @mbg.generated
     */
    List<CharacterDO> selectByParam(CharacterParam characterParam);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param characterParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") CharacterDO record, @Param("characterParam") CharacterParam characterParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param characterParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") CharacterDO record, @Param("characterParam") CharacterParam characterParam);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<CharacterDO> records);
}