-- 这张表SQ_GG_FOF_HIST_HITS
-- 从source表GG_FOF_HIST_HITS中挑选字段，此处还有取数逻辑
-- GG_OP_TYPE ： 看似是个可枚举字段，具体有哪些内容？
-- GG_BEFORE_AFTER ： 枚举类型： before ，after 两个值？
-- GG_COMMIT_TIMESTAMP ： 提交时间戳？
-- 


SELECT
    GG_FOF_HIST_HITS.GG_OP_TYPE,
    GG_FOF_HIST_HITS.SYSTEM_ID,
    GG_FOF_HIST_HITS.SEQNUMBER,
    GG_FOF_HIST_HITS.ID_LIST,
    GG_FOF_HIST_HITS.TYPE,
    GG_FOF_HIST_HITS.ORIGIN,
    GG_FOF_HIST_HITS.DESIGNATION,
    GG_FOF_HIST_HITS.KEYWORDS,
    GG_FOF_HIST_HITS.PEP,
    GG_FOF_HIST_HITS.FEP,
    GG_FOF_HIST_HITS.TAG,
    GG_FOF_HIST_HITS.NAME,
    GG_FOF_HIST_HITS.CITY,
    GG_FOF_HIST_HITS.COUNTRY,
    GG_FOF_HIST_HITS.STATE,
    GG_FOF_HIST_HITS.USERDATA1,
    GG_FOF_HIST_HITS.USERDATA2,
    GG_FOF_HIST_HITS.OFFICIALREF,
    GG_FOF_HIST_HITS.FMLTYPE,
    GG_FOF_HIST_HITS.FMLPRIORITY,
    GG_FOF_HIST_HITS.FMLCONLEVEL,
    GG_FOF_HIST_HITS.ID_REFERENCE,
    GG_FOF_HIST_HITS.FILTERINGDATE,
    GG_FOF_HIST_HITS.MATCH_LEVEL,
    GG_FOF_HIST_HITS.SIGN_KEY,
    GG_FOF_HIST_HITS.HIT_TYPE,
    GG_FOF_HIST_HITS.RECORD_MATCHING_STRING,
    GG_FOF_HIST_HITS.LIST_MATCHING_STRING,
    GG_FOF_HIST_HITS.BATCH_ID
FROM
    GG_FOF_HIST_HITS
WHERE
    (
        (GG_OP_TYPE = 'INSERT')
        OR (
            GG_OP_TYPE = 'SQL COMPUPDATE'
            AND GG_BEFORE_AFTER = 'AFTER'
        )
        OR (GG_OP_TYPE = 'DELETE')
    )
    AND GG_COMMIT_TIMESTAMP >= to_date('$$START_TIMESTAMP', 'YYYYMMDDHH24MISS')
    and GG_COMMIT_TIMESTAMP < to_date('$$END_TIMESTAMP', 'YYYYMMDDHH24MISS')